language: generic
sudo : required
services:
  - docker

before_install:
  - docker build -t burakaraca/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true burak-karaca/docker-react npm run test
